enum Keputusan {
    DIGUNAKAN = "DIGUNAKAN",
    DIPERBAIKI = 'DIPERBAIKI',
    DIKERJAKAN_ULANG = 'DIKERJAKAN_ULANG',
    PEMAKAIAN_ALTERNATIF = 'PEMAKAIAN_ALTERNATIF',
    DITOLAK = 'DITOLAK',
    TANPA_KOREKSI = 'TANPA_KOREKSI',
}

export default Keputusan;
