enum Access {
    CREATE = "CREATE",
    UPDATE_DATA = "UPDATE_DATA",
    UPDATE_SUBMIT = "UPDATE_SUBMIT",
    UPDATE_PUBLISH = "UPDATE_PUBLISH",
    DELETE = "DELETE",
    READ = "READ",
    EMAIL_SUBMIT = "EMAIL_SUBMIT"
}
export default Access;
